"use client";

import React, { useState } from "react";
import faqData from "../data/faqData";
import Question from "../components/Question";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";

const Page = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const handleToggle = (index: number) => {
    setOpenIndex((prevIndex) => (prevIndex === index ? null : index));
  };

  return (
    <div className="bg-color4 ">
      <NavBar />
      <h1 className="text-5xl font-bold mb-6 text-color1 flex justify-center pt-24">FAQ</h1>
      <div className="space-y-4">
        <h1 className="px-4 md:px-8 text-lg md:text-2xl">1. General information about Tokeshare</h1>
        <Question question="What is Tokeshare?" isOpen={openIndex === 0} onToggle={() => handleToggle(0)}>
          {
            <div>
              <p>Tokeshare is an innovative asset tokenization platform that makes it easy for anyone to invest in real estate and commodities via the blockchain. Through tokenization, Tokeshare splits physical assets into digital tokens, making investment more accessible, liquid and secure.</p>
            </div>
          }
        </Question>
        <Question question="How does Tokeshare tokenization work?" isOpen={openIndex === 1} onToggle={() => handleToggle(1)}>
          {
            <div>
              <p>Tokenization on Tokeshare is based on the conversion of physical assets, such as real estate or commodities, into digital tokens on the blockchain. This process makes it possible to divide an asset into several shares accessible to investors, offering a more affordable entry to markets traditionally reserved for large amounts of capital.</p>
              <h3 className="mb-4">Steps in the tokenization process on Tokeshare:</h3>
              <ul className="ml-4">
                <li className="mb-4">
                  <h3>1. Asset selection and valuation</h3>
                  <p className="ml-4">Tokeshare identifies and selects high-potential assets (real estate, commodities, etc) and evaluates them in terms of profitability, security and legal compliance.</p>
                </li>
                <li className="mb-4">
                  <h3>2. Tokenization</h3>
                  <p className="ml-4">Each asset is split into several digital tokens, representing a share of the real asset. For example, a property worth €200,000 can be divided into 2,000 tokens of €100 each.</p>
                </li>
                <li className="mb-4">
                  <h3>3. For sale on the platform</h3>
                  <p className="ml-4">Investors can purchase these tokens via the Tokeshare platform using cryptocurrencies or traditional currencies, according to their preferences.</p>
                </li>
                <li className="mb-4">
                  <h3>4. Receipt of income</h3>
                  <p className="ml-4">Investors receive passive income in the form of monthly stablecoin payments, generated by collected rents or commodity valuation.</p>
                </li>
                <li className="mb-4">
                  <h3>5. Liquidity and resale</h3>
                  <p className="ml-4">Tokens can be resold on the platform or to other investors, offering increased liquidity, unlike traditional investment, which is often rigid and time-consuming to liquidate.</p>
                </li>
              </ul>
            </div>
          }
        </Question>
        <Question question="What types of assets are available on the platform?" isOpen={openIndex === 2} onToggle={() => handleToggle(2)}>
          {
            <div>
              <ul>
                <li>
                  <p>Tokeshare offers fractional investment in real estate located mainly in Latin America, notably in the Dominican Republic and Argentina. These properties can include:</p>
                  <div className="ml-4 mb-4">
                    - Luxury beachfront residences, <br />
                    - Rental apartments generating passive income, <br />
                    - Commercial properties with high potential for appreciation. <br />
                  </div>
                </li>
                <li>
                  <p>Tokeshare extends investment to strategic resources, allowing investors to diversify their portfolio with:</p>
                  <div className="ml-4 mb-4">
                    - Precious Metals (Gold, Silver): Invest in certified, stocked and audited metals, with no management fees and returns based on market valuation. <br />- Agricultural products (Cocoa, Cane sugar): Access tangible assets linked to global economic cycles and consumer trends.
                  </div>
                  <div>
                    <p>Tokeshare also allows you to invest in physical businesses with high potential, such as:</p>
                    <div className="ml-4">
                      - Restaurants and bars, <br />
                      - Shops, <br />
                      - Tourism projects, <br />- Vehicle fleets (e.g. quads, scooters, rental cars).
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          }
        </Question>
        <Question question="Is Tokeshare open to investors from all over the world?" isOpen={openIndex === 3} onToggle={() => handleToggle(3)}>
          {
            <div>
              <p>Yes, Tokeshare is accessible to investors worldwide, with some exceptions due to local regulations. Thanks to blockchain technology, our platform allows investors, whether based in Europe, America, Asia or elsewhere, to acquire tokens representing real estate assets or raw materials in a simple and secure way.</p>
            </div>
          }
        </Question>

        <h1 className="px-4 md:px-8 text-lg md:text-2xl">2. Investment process</h1>
        <Question question="How can I invest on Tokeshare?" isOpen={openIndex === 4} onToggle={() => handleToggle(4)}>
          {
            <div>
              <h3 className="mb-2">Investing on Tokeshare is quick and easy. Here are the steps to follow:</h3>
              <ul className="ml-4">
                <li className="mb-2">Registration: Create an account on our platform in minutes.</li>
                <li className="mb-2">Wallet : To invest on Tokeshare, you must have a self-hosted cryptocurrency wallet, such as Metamask, Rabby Wallet, TrustWallet, Ledger, Safe, or any other compatible solution. Our platform is compatible with more than 460 wallets, giving you great flexibility of use.</li>
                <li className="mb-2">Important: Your wallet must support the Polygon or Base blockchains, as the tokenization of our assets is exclusively carried out on these networks. Before investing, make sure that your wallet is configured to interact with one of these blockchains in order to facilitate your transactions safely.Asset selection: Browse available real estate or commodities and select the one you are interested in.</li>
                <li className="mb-2">Token purchase: Invest using cryptocurrencies (stablecoins) or traditional currencies.</li>
                <li className="mb-2">Receive income: Enjoy monthly returns paid directly into your account.</li>
              </ul>
            </div>
          }
        </Question>
        <Question question="What is the minimum investment amount?" isOpen={openIndex === 5} onToggle={() => handleToggle(5)}>
          {
            <div>
              <p>The minimum investment amount on Tokeshare is $100, allowing everyone to easily access investment opportunities that were once reserved for large investors.Comment sont calculés les rendements ?</p>
            </div>
          }
        </Question>
        <Question question="How are incomes paid to investors?" isOpen={openIndex === 6} onToggle={() => handleToggle(6)}>
          {
            <div>
              <p>Income is paid monthly, directly to your Tokeshare account in the form of stablecoins (USDC), with the possibility of conversion into euros or dollars according to your preferences. A one-month lag is applied in order to optimize management.</p>
            </div>
          }
        </Question>
        <Question question="Can I sell my tokens at any time?" isOpen={openIndex === 7} onToggle={() => handleToggle(7)}>
          {
            <div>
              <p>Yes, you can sell your tokens at any time via our internal marketplace. Buyback via Tokeshare: We offer a buyback option at predefined conditions, subject to the terms in force</p>
              <p>This gives you increased flexibility and liquidity compared to traditional investing.</p>
            </div>
          }
        </Question>

        <h1 className="px-4 md:px-8 text-lg md:text-2xl">3. Safety and regulations</h1>
        <Question question="What are the risks associated with real estate tokenization?" isOpen={openIndex === 8} onToggle={() => handleToggle(8)}>
          {
            <div>
              <h3 className="mb-2">Like any investment, real estate tokenization involves certain risks, including:</h3>
              <ul className="ml-4">
                <li className="mb-2">- Market volatility: Although real estate is a relatively stable asset, its value can fluctuate depending on economic conditions and market trends.</li>
                <li className="mb-2">- Liquidity: Although tokenization improves liquidity, the resale of tokens depends on supply and demand on the platform.</li>
                <li className="mb-2">- Regulatory risks: Tokenization regulations are constantly evolving, which could impact tax or compliance requirements.</li>
                <li className="mb-2">- Technological risk: Like any blockchain-based solution, Tokeshare is exposed to risks related to cyberattacks, smart contract bugs or changes in the blockchains used.</li>
              </ul>
              <p>At Tokeshare, we put in place rigorous measures to mitigate these risks and ensure investor security.</p>
            </div>
          }
        </Question>
        <Question question="How are tokenized assets secured? Which blockchains are used for tokenization?" isOpen={openIndex === 9} onToggle={() => handleToggle(9)}>
          {
            <div>
              <h3 className="mb-2">The security of tokenized assets relies on several layers of protection:</h3>
              <ul className="ml-4">
                <li className="mb-2">- Blockchain technology: All transactions are recorded immutably and transparently on the blockchain, eliminating the risks of fraud and data alteration.</li>
                <li className="mb-2">- Audited smart contracts: Our smart contracts undergo rigorous audits to ensure their proper functioning and resistance to vulnerabilities.</li>
                <li className="mb-2">- Wallet security: Tokens are stored on decentralized wallets (Metamask, TrustWallet, Ledger, etc.), giving investors full control over their assets.</li>
                <li className="mb-2">- Physical asset security: Real estate is legally registered with guarantees and legal structures ensuring investor protection.</li>
              </ul>
            </div>
          }
        </Question>
        <Question question="Does Tokeshare guarantee a fixed return?" isOpen={openIndex === 10} onToggle={() => handleToggle(10)}>
          {
            <div>
              <h3 className="mb-2">No, Tokeshare does not guarantee a fixed return, as asset performance depends on a number of factors:</h3>
              <ul className="ml-4">
                <li className="mb-2">- Property profitability (rental income, market valuation).</li>
                <li className="mb-2">- Commodity price trends.</li>
                <li className="mb-2">- Market conditions and investor demand.</li>
              </ul>
            </div>
          }
        </Question>

        <h1 className="px-4 md:px-8 text-lg md:text-2xl">4. Costs and profitability</h1>
        <Question question="What are the fees applied on the platform?" isOpen={openIndex === 11} onToggle={() => handleToggle(11)}>
          {
            <div>
              <h3 className="mb-2">Tokeshare applies transparent and competitive fees to ensure efficient asset management and an optimal user experience. Fees include:</h3>
              <ul className="ml-4">
                <li className="mb-2">- Token purchase fee: 10% of the invested amount, covering the management and tokenization of the asset.</li>
                <li className="mb-2">- Rental fee: 2% of the monthly rental income for the management and maintenance of the real estate.</li>
                <li className="mb-2">- Token resale fee: 3% in case of redemption by Tokeshare.</li>
                <li className="mb-2">- Detokenization fee: 10% if the investor wishes to withdraw his share of the underlying asset in physical or monetary form.</li>
                <li className="mb-2">- Fixed fees for small investments: For assets under €50,000, a flat rate is applied to ensure the profitability of the operation.</li>
              </ul>
              <p>We are committed to maintaining a clear fee structure without hidden costs, in order to offer maximum transparency to investors.</p>
            </div>
          }
        </Question>

        <Question question="How is investment return calculated?" isOpen={openIndex === 12} onToggle={() => handleToggle(12)}>
          {
            <div>
              <p className="mb-2">Investment returns on Tokeshare are based on several factors:</p>
              <ul className="ml-4">
                <li className="mb-2">- Rental income (for real estate): Calculated based on the rent received, after deduction of management and maintenance fees. Returns are paid to investors in the form of stablecoins monthly.</li>
                <li className="mb-2">- Asset appreciation: The value of the property may increase over time, offering a potential capital gain upon resale.</li>
                <li className="mb-2">- Commodities and goodwill: The return is calculated based on the market value and the profits generated from the operation of the assets (e.g., renting quads or reselling raw materials).</li>
                <li className="mb-2">- Tokeshare provides detailed return projections for each asset available on the platform, allowing investors to make informed decisions.</li>
              </ul>
            </div>
          }
        </Question>

        <Question question="Are there any fees for withdrawing winnings?" isOpen={openIndex === 13} onToggle={() => handleToggle(13)}>
          {<div>No, there are no withdrawal fees on the income generated by your investments. Winnings are paid out in stablecoins directly to your cryptocurrency wallet (USDC), with the option of converting to euros or dollars as you prefer.</div>}
        </Question>

        <Question question="How Tokeshare generates revenue ?" isOpen={openIndex === 14} onToggle={() => handleToggle(14)}>
          {
            <div>
              <p className="mb-2">Tokeshare finances itself mainly through the fees charged on the platform and the optimization of the funds raised. Our sources of revenue include :</p>
              <ul className="ml-4">
                <li className="mb-2">- Transaction fees (purchase, sale, detokenization).</li>
                <li className="mb-2">- Asset management : A commission on rental income earned on real estate assets.</li>
                <li className="mb-2">- White-label solutions: We offer our technology to other companies wishing to tokenize their own assets.</li>
                <li className="mb-2">- Strategic partnerships: Collaborations with players in the real estate and financial sectors, generating additional income via commissions or asset management services.</li>
              </ul>
            </div>
          }
        </Question>

        <h1 className="px-4 md:px-8 text-lg md:text-2xl">5. Support and contact</h1>
        <Question question="How can I contact Tokeshare?" isOpen={openIndex === 15} onToggle={() => handleToggle(15)}>
          {
            <div>
              <h3 className="mb-2">You can contact us via several channels for any question or information:</h3>
              <ul className="ml-4">
                <li className="mb-2">- Email : contact@tokeshare.co</li>
                <li className="mb-2">- LinkedIn : Tokeshare on LinkedIn</li>
                <li className="mb-2">- X : @Toskehare</li>
                <li className="mb-2">- Website: tokeshare.co</li>
              </ul>
              <p>Our team is available to answer your questions and support you in your investment process.</p>
            </div>
          }
        </Question>

        <Question question="Is there dedicated customer support?" isOpen={openIndex === 16} onToggle={() => handleToggle(16)}>
          {
            <div>
              <p>Yes, Tokeshare has a dedicated customer support team, available to answer your queries by email contact@tokeshare.co</p>
            </div>
          }
        </Question>

        <Question question="Where can I follow Tokeshare news?" isOpen={openIndex === 17} onToggle={() => handleToggle(17)}>
          {
            <div>
              <h3 className="mb-2">You can follow all Tokeshare news on our various official channels:</h3>
              <ul className="ml-4">
                <li className="mb-2">- LinkedIn: Follow our latest announcements, articles and insights on tokenization.</li>
                <li className="mb-2">- Instagram : Discover our projects in pictures and follow our updates.</li>
                <li className="mb-2">- Twitter (X): Keep up to date with our latest news and market developments.</li>
                <li className="mb-2">- Our website: tokeshare.co, where we publish regular updates and case studies.</li>
              </ul>
            </div>
          }
        </Question>

        <Question question="Does Tokeshare offer guides or resources for new investors?" isOpen={openIndex === 18} onToggle={() => handleToggle(18)}>
          {
            <div>
              <h3 className="mb-2">Yes, Tokeshare provides detailed guides and educational resources to support new investors on their journey. These resources include:</h3>
              <ul className="ml-4">
                <li className="mb-2">- An introductory guide to tokenization: Explaining the concept and benefits.</li>
                <li className="mb-2">- Video tutorials: To guide you through using the platform, purchasing tokens and managing your assets.</li>
                <li className="mb-2">- Comprehensive FAQ: Answers to the most frequently asked questions about tokenization and our services.</li>
                <li className="mb-2">- Webinars and online events: Learn more and ask our experts your questions live.</li>
              </ul>
            </div>
          }
        </Question>
      </div>
      <Footer />
    </div>
  );
};

export default Page;
